### ISSUE TITLE
step2wrl.FCMacro importing freecad instead of stepup

### ISSUE THREAD

**Issue by mattisback** [SchrodingersGat/freecad-scripts#1]
For reference, I'm running this on UBUNTU 16.04.1 LTS.  Freecad version is 0.16 Revision: 6703 (Git).
I tried running the scripts as per in the example.  The first one (chain.FCMacro) worked without any problems.  The second one (step2wrl.FCMacro) however gave an error about the module `freecad` not existing.  I tried replacing it (and all references in the macro) with `FreeCAD` as that was used in the chain macro however the functions being called did not exist in that module.  After a little looking through the files in this repo I noticed that the functions in `stepup.py` have the same names as the functions being called by `freecad` in step2wrl.FCMacro.  **I replaced the module `freecad` in step2wrl.FCMacro with `stepup` and the script ran without errors and produced the desired wrl file.**
So is this some difference between linux and windows or a bug?  Should I make a pull request?

**Comment by SchrodingersGat** [comment]
@mattisback my scripts here are pretty old and (as you have found) probably do not work.

If you want to submit a PR that's fine, the issue you have found is probably endemic to Linux and Windows both.

Cheers,
